/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollectionManagement: typeof import('./src/components/CollectionManagement.vue')['default']
    CompanyOptions: typeof import('./src/components/CompanyOptions.vue')['default']
    CostControl: typeof import('./src/components/CostControl.vue')['default']
    DividerLine: typeof import('./src/components/divider/DividerLine.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    HeaderIndex: typeof import('./src/components/header/HeaderIndex.vue')['default']
    HomeApps: typeof import('./src/components/apps/HomeApps.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PaymentManagement: typeof import('./src/components/PaymentManagement.vue')['default']
    ProfitManagement: typeof import('./src/components/ProfitManagement.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    ProgressManagement: typeof import('./src/components/ProgressManagement.vue')['default']
    ProjectOptions: typeof import('./src/components/ProjectOptions.vue')['default']
    PurchasingManagement: typeof import('./src/components/PurchasingManagement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spacer: typeof import('./src/components/spacer/Spacer.vue')['default']
    TaxationManagement: typeof import('./src/components/TaxationManagement.vue')['default']
  }
}
